/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pro_kornev_kcar_protocol_Protocol */

#ifndef _Included_pro_kornev_kcar_protocol_Protocol
#define _Included_pro_kornev_kcar_protocol_Protocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pro_kornev_kcar_protocol_Protocol
 * Method:    toByteArray
 * Signature: (Lpro/kornev/kcar/protocol/Data;[B)I
 */
JNIEXPORT jint JNICALL Java_pro_kornev_kcar_protocol_Protocol_toByteArray
  (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     pro_kornev_kcar_protocol_Protocol
 * Method:    fromByteArray
 * Signature: ([BI)Lpro/kornev/kcar/protocol/Data;
 */
JNIEXPORT jobject JNICALL Java_pro_kornev_kcar_protocol_Protocol_fromByteArray
  (JNIEnv *, jclass, jbyteArray, jint);

/*
 * Class:     pro_kornev_kcar_protocol_Protocol
 * Method:    getVersion
 * Signature: ()B
 */
JNIEXPORT jbyte JNICALL Java_pro_kornev_kcar_protocol_Protocol_getVersion
  (JNIEnv *, jclass);

/*
 * Class:     pro_kornev_kcar_protocol_Protocol
 * Method:    getMaxLength
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pro_kornev_kcar_protocol_Protocol_getMaxLength
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
