/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pro_kornev_kcar_protocol_Protocol */

#ifndef _Included_pro_kornev_kcar_protocol_Protocol
#define _Included_pro_kornev_kcar_protocol_Protocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pro_kornev_kcar_protocol_Protocol
 * Method:    toByteArray
 * Signature: (Lpro/kornev/kcar/protocol/Data;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_pro_kornev_kcar_protocol_Protocol_toByteArray
  (JNIEnv *, jclass, jobject);

/*
 * Class:     pro_kornev_kcar_protocol_Protocol
 * Method:    fromByteArray
 * Signature: ([BI)Lpro/kornev/kcar/protocol/Data;
 */
JNIEXPORT jobject JNICALL Java_pro_kornev_kcar_protocol_Protocol_fromByteArray
  (JNIEnv *, jclass, jbyteArray, jint);

#ifdef __cplusplus
}
#endif
#endif
