/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pro_kornev_kcar_prototype_Protocol */

#ifndef _Included_pro_kornev_kcar_prototype_Protocol
#define _Included_pro_kornev_kcar_prototype_Protocol
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     pro_kornev_kcar_prototype_Protocol
 * Method:    toByteArray
 * Signature: (Lpro/kornev/kcar/prototype/Data;[Z)I
 */
JNIEXPORT jint JNICALL Java_pro_kornev_kcar_prototype_Protocol_toByteArray
  (JNIEnv *, jclass, jobject, jbooleanArray);

/*
 * Class:     pro_kornev_kcar_prototype_Protocol
 * Method:    fromByteArray
 * Signature: ([CI)Lpro/kornev/kcar/prototype/Data;
 */
JNIEXPORT jobject JNICALL Java_pro_kornev_kcar_prototype_Protocol_fromByteArray
  (JNIEnv *, jclass, jcharArray, jint);

#ifdef __cplusplus
}
#endif
#endif
